### ISSUE TITLE
Canada multiparcels empty response

### ISSUE THREAD

**Issue by dantedubon** [goshippo/shippo-node-client#40] opened 2017-07-13 16:42 UTC
Hi,
I am trying to setup a multiparcel shipment. My account has fedex integration and everything works fine for US and other international addresses, except for Canada. This is my request in curl (I am using the last Rest API 2017-03-29 and I got the same empty array rate list response in node):

```
curl https://api.goshippo.com/shipments/  \
-H "Content-Type: application/json" \
-H "Authorization: ShippoToken shippo_live_XXXXXXX"  \
-H "Shippo-API-Version: 2017-03-29" \
-d '{
  "object_purpose": "QUOTE",
  "address_from": {
    "name": "Burguer King",
    "street1": "2397 W Belleview Ave,",
    "city": "Littleton",
    "state": "CO",
    "zip": "80120",
    "country": "US",
    "phone": "1234567890",
    "email": "support@goshippo.com",
    "object_purpose": "QUOTE"
  },
  "address_to": {
    "name": "Random",
    "company": "",
    "street1": "5300 Rue Jean-Talon Ouest, Montreal",
    "street2": "",
    "city": "Montreal",
    "state": "QC",
    "zip": "H4P 2T5",
    "country": "CA",
    "phone": "6158328555",
    "email": "support@goshippo.com",
    "object_purpose": "QUOTE"
  },
  "parcels": [{
    "length": "18",
    "width": "13",
    "height": "12",
    "distance_unit": "in",
    "weight": "50",
    "mass_unit": "lb"
  },
  {
    "length": "14",
    "width": "11",
    "height": "6",
    "distance_unit": "in",
    "weight": "14",
    "mass_unit": "lb"
  }],
  "async": false,
  "customs_declaration": {
    "contents_type": "MERCHANDISE",
    "contents_explanation": "Shipping done easy",
    "non_delivery_option": "RETURN",
    "certify": true,
    "certify_signer": "Shippo",
    "items": [
      {
        "description": "My Parcel",
        "quantity": 1,
        "net_weight": "64",
        "mass_unit": "lb",
        "value_amount": 890.0600000000003,
        "value_currency": "USD",
        "metadata": "Your first Customs Item",
        "origin_country": "US"
      }
    ],
    "metadata": "Your first Customs Declaration"
  },
  "insurance_amount": 0,
  "insurance_currency": "USD"
}'
```

And this is my response:

```
{  
   "carrier_accounts":[  

   ],
   "object_created":"2017-07-13T16:27:44.492Z",
   "object_updated":"2017-07-13T16:27:44.492Z",
   "object_id":"436c9a73a6b64a50824aa7e067ce1acb",
   "object_owner":"XXXX",
   "status":"QUEUED",
   "address_from":{  
      "object_id":"70ecbc35d67e4de7aedf1cf8332fbc2d",
      "is_complete":false,
      "name":"Burguer King",
      "company":"",
      "street_no":"",
      "street1":"2397 W Belleview Ave,",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Littleton",
      "state":"CO",
      "zip":"80120",
      "country":"US",
      "phone":"1234567890",
      "is_residential":null,
      "test":false
   },
   "address_to":{  
      "object_id":"454d45f8ffd84a918de19233bf58c1d5",
      "is_complete":false,
      "name":"Random",
      "company":"",
      "street_no":"",
      "street1":"5300 Rue Jean-Talon Ouest, Montreal",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Montreal",
      "state":"QC",
      "zip":"H4P 2T5",
      "country":"CA",
      "phone":"6158328555",
      "is_residential":null,
      "test":false
   },
   "parcels":[  
      {  
         "object_state":"VALID",
         "object_created":"2017-07-13T16:27:44.403Z",
         "object_updated":"2017-07-13T16:27:44.512Z",
         "object_id":"eb6d416b38ab4695be4164d7dbd661d5",
         "object_owner":"XXXX",
         "template":null,
         "extra":{  

         },
         "length":"18.0000",
         "width":"13.0000",
         "height":"12.0000",
         "distance_unit":"in",
         "weight":"50.0000",
         "mass_unit":"lb",
         "value_amount":null,
         "value_currency":null,
         "metadata":"",
         "line_items":[  

         ],
         "test":false
      },
      {  
         "object_state":"VALID",
         "object_created":"2017-07-13T16:27:44.416Z",
         "object_updated":"2017-07-13T16:27:44.524Z",
         "object_id":"330b70f04269451fb3b8a4c915cd4323",
         "object_owner":"XXXX",
         "template":null,
         "extra":{  

         },
         "length":"14.0000",
         "width":"11.0000",
         "height":"6.0000",
         "distance_unit":"in",
         "weight":"14.0000",
         "mass_unit":"lb",
         "value_amount":null,
         "value_currency":null,
         "metadata":"",
         "line_items":[  

         ],
         "test":false
      }
   ],
   "shipment_date":"2017-07-13T16:27:44.402Z",
   "address_return":{  
      "object_id":"70ecbc35d67e4de7aedf1cf8332fbc2d",
      "is_complete":false,
      "name":"Burguer King",
      "company":"",
      "street_no":"",
      "street1":"2397 W Belleview Ave,",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Littleton",
      "state":"CO",
      "zip":"80120",
      "country":"US",
      "phone":"1234567890",
      "is_residential":null,
      "test":false
   },
   "customs_declaration":"e177247f08e348a4bb3b2d8871c3ba15",
   "extra":{  

   },
   "rates":[  

   ],
   "messages":[  

   ],
   "metadata":"",
   "test":false
}
```

If I send a single parcel request, I got a valid result:
The request: 
```
curl https://api.goshippo.com/shipments/  \
-H "Content-Type: application/json" \
-H "Authorization: ShippoToken shippo_live_XXXX"  \
-H "Shippo-API-Version: 2017-03-29" \
-d '{
  "object_purpose": "QUOTE",
  "address_from": {
    "name": "Burguer King",
    "street1": "2397 W Belleview Ave,",
    "city": "Littleton",
    "state": "CO",
    "zip": "80120",
    "country": "US",
    "phone": "1234567890",
    "email": "support@goshippo.com",
    "object_purpose": "QUOTE"
  },
  "address_to": {
    "name": "Random",
    "company": "",
    "street1": "5300 Rue Jean-Talon Ouest, Montreal",
    "street2": "",
    "city": "Montreal",
    "state": "QC",
    "zip": "H4P 2T5",
    "country": "CA",
    "phone": "6158328555",
    "email": "support@goshippo.com",
    "object_purpose": "QUOTE"
  },
  "parcels": [{
    "length": "18",
    "width": "13",
    "height": "12",
    "distance_unit": "in",
    "weight": "50",
    "mass_unit": "lb"
  }],
  "async": false,
  "customs_declaration": {
    "contents_type": "MERCHANDISE",
    "contents_explanation": "Shipping done easy",
    "non_delivery_option": "RETURN",
    "certify": true,
    "certify_signer": "Shippo",
    "items": [
      {
        "description": "My Parcel",
        "quantity": 1,
        "net_weight": "50",
        "mass_unit": "lb",
        "value_amount": 890.0600000000003,
        "value_currency": "USD",
        "metadata": "Your first Customs Item",
        "origin_country": "US"
      }
    ],
    "metadata": "Your first Customs Declaration"
  },
  "insurance_amount": 0,
  "insurance_currency": "USD"
}'
```

And the response:

```
{  
   "carrier_accounts":[  

   ],
   "object_created":"2017-07-13T16:36:58.549Z",
   "object_updated":"2017-07-13T16:36:58.549Z",
   "object_id":"2bc4f52c06b349d195ca7044d032f20d",
   "object_owner":"XXX",
   "status":"SUCCESS",
   "address_from":{  
      "object_id":"7e82b6eda8354315889b31c22b8ddebe",
      "is_complete":false,
      "name":"Burguer King",
      "company":"",
      "street_no":"",
      "street1":"2397 W Belleview Ave,",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Littleton",
      "state":"CO",
      "zip":"80120",
      "country":"US",
      "phone":"1234567890",
      "is_residential":null,
      "test":false
   },
   "address_to":{  
      "object_id":"b5e4ab73bda24367bd9f9453b832c56e",
      "is_complete":false,
      "name":"Random",
      "company":"",
      "street_no":"",
      "street1":"5300 Rue Jean-Talon Ouest, Montreal",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Montreal",
      "state":"QC",
      "zip":"H4P 2T5",
      "country":"CA",
      "phone":"6158328555",
      "is_residential":null,
      "test":false
   },
   "parcels":[  
      {  
         "object_state":"VALID",
         "object_created":"2017-07-13T16:36:58.495Z",
         "object_updated":"2017-07-13T16:36:58.561Z",
         "object_id":"222eb6fb4cf64188bd52d396cbb512ac",
         "object_owner":"XXX",
         "template":null,
         "extra":{  

         },
         "length":"18.0000",
         "width":"13.0000",
         "height":"12.0000",
         "distance_unit":"in",
         "weight":"50.0000",
         "mass_unit":"lb",
         "value_amount":null,
         "value_currency":null,
         "metadata":"",
         "line_items":[  

         ],
         "test":false
      }
   ],
   "shipment_date":"2017-07-13T16:36:58.495Z",
   "address_return":{  
      "object_id":"7e82b6eda8354315889b31c22b8ddebe",
      "is_complete":false,
      "name":"Burguer King",
      "company":"",
      "street_no":"",
      "street1":"2397 W Belleview Ave,",
      "validation_results":{  

      },
      "street2":"",
      "street3":"",
      "city":"Littleton",
      "state":"CO",
      "zip":"80120",
      "country":"US",
      "phone":"1234567890",
      "is_residential":null,
      "test":false
   },
   "customs_declaration":"5238ff2c03644d2fa334967f19770a8f",
   "extra":{  

   },
   "rates":[  
      {  
         "object_created":"2017-07-13T16:36:59.567Z",
         "object_id":"8085fd203d514fc38a1e3f31194ea617",
         "object_owner":"XXXX",
         "shipment":"2bc4f52c06b349d195ca7044d032f20d",
         "attributes":[  
            "BESTVALUE",
            "CHEAPEST"
         ],
         "amount":"76.36",
         "currency":"USD",
         "amount_local":"97.36",
         "currency_local":"CAD",
         "provider":"FedEx",
         "provider_image_75":"https://shippo-static.s3.amazonaws.com/providers/75/FedEx.png",
         "provider_image_200":"https://shippo-static.s3.amazonaws.com/providers/200/FedEx.png",
         "servicelevel":{  
            "name":"Ground",
            "token":"fedex_ground",
            "terms":""
         },
         "days":4,
         "arrives_by":null,
         "duration_terms":"",
         "messages":[  

         ],
         "carrier_account":"1bce1c5b1bf840668670eaeab8702250",
         "test":false,
         "zone":"51"
      },
      {  
         "object_created":"2017-07-13T16:36:59.566Z",
         "object_id":"5133924de4cd4b7abd3396d2ca261fa4",
         "object_owner":"XXX",
         "shipment":"2bc4f52c06b349d195ca7044d032f20d",
         "attributes":[  

         ],
         "amount":"110.13",
         "currency":"USD",
         "amount_local":"140.41",
         "currency_local":"CAD",
         "provider":"FedEx",
         "provider_image_75":"https://shippo-static.s3.amazonaws.com/providers/75/FedEx.png",
         "provider_image_200":"https://shippo-static.s3.amazonaws.com/providers/200/FedEx.png",
         "servicelevel":{  
            "name":"International Economy",
            "token":"fedex_international_economy",
            "terms":""
         },
         "days":4,
         "arrives_by":null,
         "duration_terms":"0:00 A.M. IF NO CUSTOMS DELAY",
         "messages":[  

         ],
         "carrier_account":"1bce1c5b1bf840668670eaeab8702250",
         "test":false,
         "zone":"US001O"
      },
      {  
         "object_created":"2017-07-13T16:36:59.566Z",
         "object_id":"33f2a81d925e4939a82b2d001a76435f",
         "object_owner":"XXXX",
         "shipment":"2bc4f52c06b349d195ca7044d032f20d",
         "attributes":[  
            "FASTEST"
         ],
         "amount":"126.76",
         "currency":"USD",
         "amount_local":"161.62",
         "currency_local":"CAD",
         "provider":"FedEx",
         "provider_image_75":"https://shippo-static.s3.amazonaws.com/providers/75/FedEx.png",
         "provider_image_200":"https://shippo-static.s3.amazonaws.com/providers/200/FedEx.png",
         "servicelevel":{  
            "name":"International Priority",
            "token":"fedex_international_priority",
            "terms":""
         },
         "days":2,
         "arrives_by":null,
         "duration_terms":"0:00 A.M. IF NO CUSTOMS DELAY",
         "messages":[  

         ],
         "carrier_account":"1bce1c5b1bf840668670eaeab8702250",
         "test":false,
         "zone":"US001O"
      }
   ],
   "messages":[  
      {  
         "source":"FedEx",
         "code":"820",
         "text":"NOTE: The destination state/province code has been changed.  "
      },
      {  
         "source":"FedEx",
         "code":"886",
         "text":"NOTE: Money Back Guarantee is not eligible for this pick up/delivery postal/zip code. "
      }
   ],
   "metadata":"",
   "test":false
}
```

Thanks in advance

**Comment by mootrichard** [comment] 2017-07-13 20:33
@dantedubon we are currently working on an issue with Multipiece International shipments that will resolve the issue that you're encountering. I don't have an ETA of when it will be fixed, but it is currently scheduled in our most current sprint.

**Comment by dantedubon** [comment] 2017-07-18 17:39
Can we have a time estimate about it? @mootrichard

**Comment by mootrichard** [comment] 2017-07-18 22:39
So we just had a fix for this being merged and tested, so I think that within approximately a week it should be released if all is well.

**Comment by cfontecha** [comment] 2017-08-09 16:12
Has the fix been released?

**Comment by mootrichard** [comment] 2017-08-14 18:37
Yes, this fix has been released and should be working as intended for international multi-piece shipments! Thanks for checking back on this, I will close this out now.

**Closed by mootrichard** 2017-08-14 18:37 UTC
